### ISSUE TITLE
any program to produce the mask image?

### ISSUE THREAD

**Issue by andyhx** [taivop/shih-styletransfer#2]
I want what part of code is to create the mask image,thanks

**Comment by andyhx** [comment]
I got that ,graphcut method ,But I wonder what
 is 66 landmarks  , It seems that many people now  using 68 or 5 points ,what is difference between 68 landmarks

**Comment by Liforam** [comment]
Can you tell me how to get the mask image and the background image?

**Comment by taivop** [comment]
None of this is my work and I am in no way related to the authors; I simply mirrored the original paper's code to GitHub.
